/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as EmbassiesRouteImport } from './routes/embassies'
import { Route as GpaConversionRouteImport } from './routes/gpa-conversion'
import { Route as OrientationRouteImport } from './routes/orientation'
import { Route as PaperWorkRouteImport } from './routes/paper-work'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as RequestCodeRouteImport } from './routes/request-code'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as UniversityIdRouteImport } from './routes/university.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbassiesRoute = EmbassiesRouteImport.update({
  id: '/embassies',
  path: '/embassies',
  getParentRoute: () => rootRouteImport,
} as any)
const GpaConversionRoute = GpaConversionRouteImport.update({
  id: '/gpa-conversion',
  path: '/gpa-conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientationRoute = OrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperWorkRoute = PaperWorkRouteImport.update({
  id: '/paper-work',
  path: '/paper-work',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestCodeRoute = RequestCodeRouteImport.update({
  id: '/request-code',
  path: '/request-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityIdRoute = UniversityIdRouteImport.update({
  id: '/university/$id',
  path: '/university/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admissions': typeof AdmissionsRoute
  '/embassies': typeof EmbassiesRoute
  '/gpa-conversion': typeof GpaConversionRoute
  '/orientation': typeof OrientationRoute
  '/paper-work': typeof PaperWorkRoute
  '/partners': typeof PartnersRoute
  '/request-code': typeof RequestCodeRoute
  '/scholarships': typeof ScholarshipsRoute
  '/universities': typeof UniversitiesRoute
  '/university/$id': typeof UniversityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admissions': typeof AdmissionsRoute
  '/embassies': typeof EmbassiesRoute
  '/gpa-conversion': typeof GpaConversionRoute
  '/orientation': typeof OrientationRoute
  '/paper-work': typeof PaperWorkRoute
  '/partners': typeof PartnersRoute
  '/request-code': typeof RequestCodeRoute
  '/scholarships': typeof ScholarshipsRoute
  '/universities': typeof UniversitiesRoute
  '/university/$id': typeof UniversityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admissions': typeof AdmissionsRoute
  '/embassies': typeof EmbassiesRoute
  '/gpa-conversion': typeof GpaConversionRoute
  '/orientation': typeof OrientationRoute
  '/paper-work': typeof PaperWorkRoute
  '/partners': typeof PartnersRoute
  '/request-code': typeof RequestCodeRoute
  '/scholarships': typeof ScholarshipsRoute
  '/universities': typeof UniversitiesRoute
  '/university/$id': typeof UniversityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admissions'
    | '/embassies'
    | '/gpa-conversion'
    | '/orientation'
    | '/paper-work'
    | '/partners'
    | '/request-code'
    | '/scholarships'
    | '/universities'
    | '/university/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admissions'
    | '/embassies'
    | '/gpa-conversion'
    | '/orientation'
    | '/paper-work'
    | '/partners'
    | '/request-code'
    | '/scholarships'
    | '/universities'
    | '/university/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admissions'
    | '/embassies'
    | '/gpa-conversion'
    | '/orientation'
    | '/paper-work'
    | '/partners'
    | '/request-code'
    | '/scholarships'
    | '/universities'
    | '/university/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdmissionsRoute: typeof AdmissionsRoute
  EmbassiesRoute: typeof EmbassiesRoute
  GpaConversionRoute: typeof GpaConversionRoute
  OrientationRoute: typeof OrientationRoute
  PaperWorkRoute: typeof PaperWorkRoute
  PartnersRoute: typeof PartnersRoute
  RequestCodeRoute: typeof RequestCodeRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  UniversitiesRoute: typeof UniversitiesRoute
  UniversityIdRoute: typeof UniversityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embassies': {
      id: '/embassies'
      path: '/embassies'
      fullPath: '/embassies'
      preLoaderRoute: typeof EmbassiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpa-conversion': {
      id: '/gpa-conversion'
      path: '/gpa-conversion'
      fullPath: '/gpa-conversion'
      preLoaderRoute: typeof GpaConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientation': {
      id: '/orientation'
      path: '/orientation'
      fullPath: '/orientation'
      preLoaderRoute: typeof OrientationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper-work': {
      id: '/paper-work'
      path: '/paper-work'
      fullPath: '/paper-work'
      preLoaderRoute: typeof PaperWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-code': {
      id: '/request-code'
      path: '/request-code'
      fullPath: '/request-code'
      preLoaderRoute: typeof RequestCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/$id': {
      id: '/university/$id'
      path: '/university/$id'
      fullPath: '/university/$id'
      preLoaderRoute: typeof UniversityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdmissionsRoute: AdmissionsRoute,
  EmbassiesRoute: EmbassiesRoute,
  GpaConversionRoute: GpaConversionRoute,
  OrientationRoute: OrientationRoute,
  PaperWorkRoute: PaperWorkRoute,
  PartnersRoute: PartnersRoute,
  RequestCodeRoute: RequestCodeRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  UniversitiesRoute: UniversitiesRoute,
  UniversityIdRoute: UniversityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
